
export enum NoteStatus {
  DRAFT = 'DRAFT',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  RETURNED = 'RETURNED',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  SENT = 'SENT',
  ARCHIVED = 'ARCHIVED'
}

export enum UserRole {
  REDACTEUR = 'REDACTEUR',
  CHEF_DEPARTEMENT = 'CHEF_DEPARTEMENT',
  DIRECTEUR_EXECUTIF = 'DIRECTEUR_EXECUTIF',
  DESTINATAIRE = 'DESTINATAIRE',
  ADMIN = 'ADMIN'
}